# Generated by Django 5.0.4 on 2024-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_alter_points_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='points_type',
            field=models.CharField(choices=[('GB Pounds', 'GB Pounds'), ('US dollars', 'US dollars'), ('Euros', 'Euros')], default='GB Pounds', max_length=12),
        ),
    ]
