# Generated by Django 5.0.4 on 2024-04-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_points_points_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.FloatField(default=1000),
        ),
    ]
