# Generated by Django 5.0.4 on 2024-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_alter_points_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransfer',
            name='enter_points_to_transfer',
            field=models.FloatField(),
        ),
    ]
