# Generated by Django 5.0.4 on 2024-04-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_alter_pointstransfer_enter_points_to_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointstransfer',
            name='enter_points_to_transfer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
