# Generated by Django 5.0.4 on 2024-04-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_alter_points_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='pointstransfer',
            name='enter_points_to_transfer',
            field=models.FloatField(),
        ),
    ]
