# Generated by Django 5.0.4 on 2024-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0008_pointsrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
