# Generated by Django 5.0.4 on 2024-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0010_remove_pointsrequest_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsrequest',
            name='transfer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=12),
        ),
    ]
