# Generated by Django 5.0.4 on 2024-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0011_alter_pointsrequest_transfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrequest',
            name='currency_type',
            field=models.CharField(default='GB Pounds', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointstransfer',
            name='currency_type',
            field=models.CharField(default='GB Pounds', max_length=50),
            preserve_default=False,
        ),
    ]
