# Generated by Django 5.0.4 on 2024-04-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0012_pointsrequest_currency_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsrequest',
            old_name='currency_type',
            new_name='Points_type',
        ),
        migrations.RenameField(
            model_name='pointstransfer',
            old_name='currency_type',
            new_name='points_type',
        ),
    ]
