# Generated by Django 5.0.4 on 2024-04-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0013_rename_currency_type_pointsrequest_points_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsrequest',
            old_name='Points_type',
            new_name='points_type',
        ),
    ]
