# Generated by Django 5.0.4 on 2024-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0014_rename_points_type_pointsrequest_points_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrequest',
            name='date_time',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointstransfer',
            name='date_time',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
